In [46]:
#Import the libraries
import pandas as df
import numpy as np

In [51]:
#Q1. Pandas version
print(f'Pandas version: {pd.__version__}')

Pandas version: 2.2.3

In [53]:
#Q2. Records count
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
print(f'There are {len(df)} records')

There are 10000 records

In [55]:
#Q3. Fuel types
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [56]:
#Q4. Missing values
incomplete_columns = df.columns[df.isnull().any()].tolist()

print(incomplete_columns)

['horsepower', 'acceleration']

In [57]:
#Q5. Max fuel efficiency
asian_cars = df[df['origin'] == 'Asia']
max_val = asian_cars['fuel_efficiency_mpg'].max()
print('The maximun value of fuel efficiency is', max_val)
asian_cars

The maximun value of fuel efficiency is 41.2

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [60]:
#Q6. Median value of horsepower
mean_before = df['horsepower'].mean()
print(f'The mean before fill missing values is {mean_before:.2f}')
mode = df['horsepower'].mode()[0]
print(f'The most frequent value is', mode)

df['horsepower'] = df['horsepower'].fillna(mode)
mean_after = df['horsepower'].mean()
print(f'The mean after fill missing values is {mean_after:.2f}')
df['horsepower']
if mean_before == mean_after:
    print('The mean doesnt change.')
elif mean_before > mean_after:
    print('The mean decrease.')
else:
    print('The mean increase.')

The mean before fill missing values is 254.23
The most frequent value is 252.0
The mean after fill missing values is 254.23
The mean doesnt change.

In [59]:
#Q7. Sum of weights
asian_cars = df[df['origin'] == 'Asia']
d_filter = asian_cars[['vehicle_weight', 'model_year']].head(7)

x = d_filter.to_numpy()

XTX = np.dot(x.T, x)

XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = np.dot(np.dot(XTX_inv, x.T), y)

sum_w = np.sum(w)

print("Weights vector is:", w)
print("The sum of all the elements is:", sum_w)

Weights vector is: [0.13644777 0.2327492 ]
The sum of all the elements is: 0.36919696904925486